# SPDX-License-Identifier: BSD-3-Clause
#
# Makefile.params
#

export HDL_DEFINES = +define+SIMULATION=1
export HDL_PARAMS = \
	-pvalue+cosim_p=$(COSIM_P) \
	-pvalue+checkpoint_p=$(CHECKPOINT_P) \
	-pvalue+cosim_memsize_p=$(COSIM_MEMSIZE_P) \
	-pvalue+cosim_instr_p=$(COSIM_INSTR_P) \
	-pvalue+commit_trace_p=$(COMMIT_TRACE_P)

